title: Mencari Medok
description: Catatan rasa, kota, dan arsip kecil yang tetap medok.
lang: id

# User Pages (repo: mencarimedok.github.io)
url: "https://mencarimedok.github.io"
baseurl: ""

markdown: kramdown
permalink: /:year/:month/:day/:title/

excerpt_separator: "<!--more-->"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# (opsional) isi setelah kamu dapat dari Google Search Console:
# google_site_verification: "PASTE_TOKEN_DI_SINI"
